language: c++
os:
        - linux
        - osx

compiler:
        - gcc

notifications:
        email:
                on_success: change
                on_failure: always

before_install:
        - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
        - sudo apt-get update -qq

install:
        # install g++ 5, if tests are run with g++
        - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-5; fi
        - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50; fi

        # Google test framework
        - sudo apt-get install -qq libgtest-dev
        - cd /usr/src/gtest
        - sudo cmake .
        - sudo make
        - sudo mv libgtest* /usr/lib/
        - cd "${TRAVIS_BUILD_DIR}"

        # SDL2
        - wget libsdl.org/release/SDL2-2.0.3.tar.gz
        - tar -xf SDL2-2.0.3.tar.gz
        - cd SDL2-2.0.3
        - ./configure
        - make -j 4
        - sudo make install
        - cd "${TRAVIS_BUILD_DIR}"

        # SDL2_image
        - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
        - tar -xf SDL2_image-2.0.0.tar.gz
        - cd SDL2_image-2.0.0
        - ./configure
        - make -j 4
        - sudo make install
        - cd "${TRAVIS_BUILD_DIR}"

        # ImgaeMagick++
        - sudo apt-get install -qq libgraphicsmagick++1-dev libgraphicsmagick++3 libmagick++-dev libmagick++4

after_install:
        - sudo ldconfig

script:
        - make all
        - make runTest
